apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Cert-Manager
# - ../common/cert-manager/cert-manager/base # this installs cert manager itself
- ../common/cert-manager/kubeflow-issuer/base # this creates a known issuer for kubeflow to use
# Istio
# - ../common/istio-1-16/istio-crds/base # this installs the custom resources istio relies on
# - ../common/istio-1-16/istio-namespace/base # this creates istios namespace
# - ../common/istio-1-16/istio-install/base # this installs istio itself
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
# - ../common/dex/overlays/istio # deploys and configures a dex service
# KNative
# - ../common/knative/knative-serving/overlays/gateways # installs knative serving and creates gateways
# - ../common/knative/knative-eventing/base # installs knative eventing
# - ../common/istio-1-16/cluster-local-gateway/base # creates istion knative gateway and netpols?
# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-16/kubeflow-istio-resources/base # creates istio gateway for kubeflow specific resources


# Kubeflow Pipelines
- ../apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
# Katib
- ../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook
- ../apps/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller
- ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
-  ../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
-  ../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../common/user-namespace/base

# KServe
# - ../contrib/kserve/kserve
- ../contrib/kserve/models-web-app/overlays/kubeflow
